l_german:
 DIVISION_QUEUED:0 "$N$ Einheit"
 DIVISIONS_QUEUED:0 "$N$ Einheiten"
 ARMY_LEDGER_ARMIES:1 "Einheiten"
 ARMY_LEDGER_THRESHOLD_EQUIPMENT_RATIO:1 "Durchschnittliche Ausrüstungsvollständigkeit der Einheiten im Feld"
 ARMY_LEDGER_THRESHOLD_BASIC_TEMPLATE_INFO:1 "Liste der Einheitenvorlagen"
 ARMY_LEDGER_THRESHOLD_FUZZY_TEMPLATE_COUNT:1 "Ungefähre Anzahl Einheiten pro Vorlage"
 ARMY_LEDGER_THRESHOLD_TEMPLATE_COUNT:1 "Anzahl Einheiten pro Vorlage"
 TRIGGER_DIVISIONS_MORE_THAN:0 "Hat mehr als $AMOUNT|H$ Einheiten"
 TRIGGER_DIVISIONS_LESS_THAN:0 "Hat mindestens $AMOUNT|H$ Einheiten"
 TRIGGER_DIVISIONS:0 "Einheiten"
 DIVISIONS:0 "Einheiten"
 DIVISIONS_COUNTRY:0 "§T$COUNTRY|H$ hat $VAL|H$ Einheiten§!"
 ARMY_TAB:0 "Einheiten"
 TOPBAR_ARMY_DESC:0 "Siehe eine Übersicht über deine Armee."
 COMBAT_COMMITED_LABEL:0 "$COUNT$ Einheiten"
 ARMY_ARMY_LABEL:0 "Einheitenübersicht"
 ARMY_DIVISONS_TAB:0 "§YEinheiten§!"
 ARMY_DIVISIONS_ACTIVE:0 "$N$ Kampfeinheiten"
 ARMY_DIVISIONS_BUTTON:0 "§GKlicke§! zum auswählen.\n§GKlicke§! und §Hhalte Shift§! um mehrere Einheiten auszuwählen.\n§GRechtsklicke§! um zur Einheit zu schwenken."
 EXP_MULTIPLE_DIVISIONS:0 "$COUNT$/$TOTAL$ Einheiten"
 EXP_SINGLE_DIVISION:0 "1 Einheit"
 VOL_MULTIPLE_DIVISIONS:0 "$COUNT$ Einheiten"
 VOL_SINGLE_DIVISION:0 "1 Einheit"
 LEDGER_DIVISIONS: "Einheiten"
 REQUEST_EXPEDITIONARIES_DIVISIONS_COUNT:0 "$NUM_DIVS|Y$ Einheiten insgesamt"
 UNITS_VIEW_DIVISIONS_COUNT:0 "$DIV|G$ Einheiten"