l_korean:
 DIVISION_QUEUED:0 "$N$ 부대"
 DIVISIONS_QUEUED:0 "$N$ 부대"
 ARMY_LEDGER_ARMIES:1 "병력"
 ARMY_LEDGER_THRESHOLD_EQUIPMENT_RATIO:1 "주둔 사단의 보급된 장비 비율"
 ARMY_LEDGER_THRESHOLD_BASIC_TEMPLATE_INFO:1 "사단 편제 목록"
 ARMY_LEDGER_THRESHOLD_FUZZY_TEMPLATE_COUNT:1 "대략적인 편제당 사단 수"
 ARMY_LEDGER_THRESHOLD_TEMPLATE_COUNT:1 "편제당 사단 수"
 TRIGGER_DIVISIONS_MORE_THAN:0 "$AMOUNT|H$개 사단 초과"
 TRIGGER_DIVISIONS_LESS_THAN:0 "최소 $AMOUNT|H$개 사단"
 TRIGGER_DIVISIONS:0 "병력"
 DIVISIONS:0 "병력"
 DIVISIONS_COUNTRY:0 "§T$COUNTRY|H$ 측은 $VAL|H$개 사단 보유§!"
 ARMY_TAB:0 "병력"
 TOPBAR_ARMY_DESC:0 "사단의 개요를 봅니다."
 COMBAT_COMMITED_LABEL:0 "$COUNT$ 병력"
 ARMY_ARMY_LABEL:0 "사단 개요"
 ARMY_DIVISONS_TAB:0 "§Y병력§!"
 ARMY_DIVISIONS_ACTIVE:0 "$N$ 전투 사단"
 ARMY_DIVISIONS_BUTTON:0 "§G클릭§!으로 선택합니다.\n§HShift를 누른채로§! §G클릭§!해서 여러 사단을 선택합니다.\n§G우클릭§!으로 사단을 재배정 합니다."
 EXP_MULTIPLE_DIVISIONS:0 "$COUNT$/$TOTAL$ 사단"
 EXP_SINGLE_DIVISION:0 "1 병력"
 VOL_MULTIPLE_DIVISIONS:0 "$COUNT$ 병력"
 VOL_SINGLE_DIVISION:0 "1 병력"
 LEDGER_DIVISIONS: "병력"
 REQUEST_EXPEDITIONARIES_DIVISIONS_COUNT:0 "$NUM_DIVS|Y$ 총 사단"
 UNITS_VIEW_DIVISIONS_COUNT:0 "$DIV|G$ 사단"