title: "Millennium Dawn"
description: "Documentation for the Millennium Dawn mod for Hearts of Iron IV"
baseurl: "/Millennium-Dawn"
url: "https://millenniumdawnmod.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

collections:
  guides:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - title: "Home"
    url: "/"
  - title: "FAQ"
    url: "/faq"
  - title: "Support"
    url: "/technical-support"
  - title: "Tutorials"
    url: "/tutorials"
  - title: "Resources"
    url: "/team-resources"
  - title: "Changelogs"
    url: "/changelogs"
  - title: "Dev Diaries"
    url: "/dev-diaries-list"
  - title: "Country List"
    url: "/countries-list"
  - title: "Code Style Guide"
    url: "/dev-resources/code-stylization-guide"

social:
  - name: "GitHub"
    url: "https://github.com/MillenniumDawn/Millennium-Dawn"
  - name: "Steam Workshop"
    url: "https://steamcommunity.com/sharedfiles/filedetails/?id=2777392649"
  - name: "Reddit"
    url: "https://www.reddit.com/r/MillenniumDawn/"
  - name: "Discord"
    url: "https://discord.gg/millenniumdawn"
  - name: "Twitter"
    url: "https://twitter.com/MillenniumDawn"
